In [ ]:
pip install numpy

In [2]:
import numpy as np
import numpy.random as npr

In [3]:
A=(np.arange(64)+1).reshape((8,8))
print(A)
print(A.shape)
A.resize(8,4,2)
print(A)
print(A.shape)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56]
 [57 58 59 60 61 62 63 64]]
(8, 8)
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]

 [[17 18]
  [19 20]
  [21 22]
  [23 24]]

 [[25 26]
  [27 28]
  [29 30]
  [31 32]]

 [[33 34]
  [35 36]
  [37 38]
  [39 40]]

 [[41 42]
  [43 44]
  [45 46]
  [47 48]]

 [[49 50]
  [51 52]
  [53 54]
  [55 56]]

 [[57 58]
  [59 60]
  [61 62]
  [63 64]]]
(8, 4, 2)


In [4]:
A=np.arange(10000)+1
B=A[1::2]
print(B)

[    2     4     6 ...  9996  9998 10000]


In [5]:
import numpy as np
from google.colab import drive
drive.mount('/content/drive')

train_data_path="/content/drive/MyDrive/인공지능 중간 레포트/train_data.npy"
train_label_path="/content/drive/MyDrive/인공지능 중간 레포트/train_label.npy"

train_data=np.load(train_data_path,allow_pickle=True)
train_data_rawdata=np.load(train_label_path,allow_pickle=True)

num_train_data=len(train_data)

Mounted at /content/drive


In [7]:
max_len=-1
max_index=None
min_len=10000000
min_index=None

for index, lists in enumerate(train_data):
  list_len=len(lists)
  if(list_len>max_len):
    max_index=index
    max_len=list_len
  if(list_len<min_len):
    min_index=index
    min_len=list_len

print("shortest index : %d, shortest length : %d"%(min_index,min_len))
print("longest index: %d, longest length : %d"%(max_index,max_len))

shortest index : 2511, shortest length : 16
longest index: 2678, longest length : 502


In [8]:
import random

count=0;
check=[]

for each_game in train_data[random.randrange(len(train_data))]:
  if(count>=10):
    break
  each_game.resize(19,19)
  for row_index, row_list in enumerate(each_game):
    if(count>=10):
      break
    for col_index, col_element in enumerate(row_list):
      if(count>=10):
        break
      cur_point=[row_index,col_index]
      if(col_element!=0 and cur_point not in check):
        print("%dst : [%d, %d]"%(count+1, row_index,col_index))
        check.append(cur_point)
        count+=1

1st : [16, 16]
2st : [2, 16]
3st : [16, 2]
4st : [2, 3]
5st : [4, 2]
6st : [3, 2]
7st : [4, 3]
8st : [3, 5]
9st : [8, 2]
10st : [14, 15]


In [18]:
max_b=-1
max_all=0
max_index=0

for game_index, game in enumerate(train_data):
  datalen=len(game)
  last_game=game[datalen-1]
  last_game.resize(19,19)
  all_count=0
  b_count=0

  for row_index, row in enumerate(last_game):
    for col_index, element in enumerate(row):
      if(element!=0):
        if(row_index<9 and col_index<9):
          b_count+=1
        all_count+=1

  if(b_count>max_b):
    max_b=b_count
    max_all=all_count
    max_index=game_index

print("max B index :%d"%(max_index))
print("max B : %d, A : %d, B/A : %.4f"%(max_b,max_all,max_b/max_all))

max B index :272
max B : 75, A : 325, B/A : 0.2308
